--
-- Dumping data for table `wp_book_authors`
--

INSERT INTO `wp_book_authors` (`id`, `name`, `fb_link`, `about`, `created_at`) VALUES
(1, 'Dennis Mark', 'https://fb.me/dennis-mark', 'Fusce ultricies tellus quis purus accumsan sollicitudin. In enim diam, eleifend et quam non, lacinia dictum velit. Phasellus porta, neque sit amet dignissim tempor.', '2021-08-03 16:37:41'),
(2, 'Andrew Sons', 'https://fb.me/andrew-sons', 'Praesent eget leo accumsan, volutpat dui a, consequat ex. Vestibulum nulla libero, condimentum non egestas vel, suscipit sit amet nunc. Cras nec scelerisque libero.', '2021-08-03 16:37:53'),
(3, 'Michael Jones', 'https://fb.me/michael-jones', 'Curabitur laoreet nulla eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '2021-08-03 16:38:05'),
(4, 'Albert Kark', 'https://fb.me/albert-kark', 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.', '2021-08-03 16:38:21'),
(5, 'Mandia Karw', 'https://fb.me/mandia-karw', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla at blandit leo. Nullam quis volutpat arcu. Nullam aliquet sed velit id tempus. Suspendisse sodales et turpis sed bibendum.', '2021-08-03 16:38:33');


--
-- Dumping data for table `wp_book_books`
--

INSERT INTO `wp_book_books` (`id`, `name`, `author_id`, `about`, `book_image`, `created_at`) VALUES
(1, 'C Programming', 1, 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \\\"de Finibus Bonorum et Malorum\\\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \\\"Lorem ipsum dolor sit amet..\\\", comes from a line in section 1.10.32.', 'http://wp-plugindev-demo.local/wp-content/uploads/2021/08/cpp.jpg', '2021-08-03 16:41:34'),
(2, 'Java Programming', 2, 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\\\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\\\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 'http://wp-plugindev-demo.local/wp-content/uploads/2021/08/java-3a-the-complete-reference-seventh-edition-500x500-1.png', '2021-08-03 16:42:08'),
(3, 'HTML 5', 2, 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \\\'Content here, content here\\\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \\\'lorem ipsum\\\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', 'http://wp-plugindev-demo.local/wp-content/uploads/2021/08/html.jpg', '2021-08-03 16:43:00'),
(4, 'PHP Core', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum', 'http://wp-plugindev-demo.local/wp-content/uploads/2021/08/php.jpg', '2021-08-03 16:43:38'),
(5, 'Python', 3, 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ', 'http://wp-plugindev-demo.local/wp-content/uploads/2021/08/python.jpg', '2021-08-03 16:44:21'),
(6, 'JavaScript', 2, 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally', 'http://wp-plugindev-demo.local/wp-content/uploads/2021/08/Javascript.jpg', '2021-08-03 16:45:58');
